name: Generate image tag
description: Creates a consitent image tag for our docker images
inputs:
  environment-prefix:
    description: Environment of the image being built to be used as a prefix at the start of the tag
    required: true
outputs:
  tag:
    description: The generated image tag with optional prefixes
    value: ${{ steps.generate-image-tag.tag }}
runs:
  using: composite
  steps:
    - name: Generate image tag
      id: generate-image-tag
      shell: bash
      run: echo "::set-output name=tag::${{ inputs.environment-prefix }}-$(git rev-parse --short=8 HEAD)"
