name: Prepare Elastic Beanstalk version
description:
  Creates a EB single-container docker version source, a zip of the
  Dockerrun.aws.json and the .ebextensions folder
inputs:
  image-ecr-url:
    description: The ECR url of the docker image
    required: true
  destination-s3-url:
    description: The destination S3 URL to upload the deployment zip to
    required: true
  ebextensions-folder:
    description: The path of the .ebextensions folder
    required: false
    default: .ebextensions
runs:
  using: composite
  steps:
    - name: Create EB Dockerrun.aws.json
      shell: bash
      run: |
        cat > /tmp/Dockerrun.aws.json << ENDOFFILE
          {
            "AWSEBDockerrunVersion": "1",
            "Image": {
              "Name": "${{ inputs.image-ecr-url }}",
              "Update": "true"
            },
            "Volumes": [
              {
                "HostDirectory": "/var/log/docker-container",
                "ContainerDirectory": "/app/log"
              }
            ],
            "Ports": [
              {
                "ContainerPort": "3000",
                "HostPort": "80"
              }
            ]
          }
        ENDOFFILE
    - name: Create zip with Dockerrun.aws.json & .ebextensions/
      shell: bash
      run: |
        cp -R ${{ inputs.ebextensions-folder-path }} /tmp/.ebextensions
        cd /tmp
        zip -r docker.zip Dockerrun.aws.json .ebextensions
    - name: Upload EB zip to S3
      shell: bash
      run: |
        aws s3 cp /tmp/docker.zip ${{ inputs.destination-s3-url }}
